#!/bin/sh

#  Script.sh
#  PageRanks
#
#  Created by Dylan on 24/7/19.
#  Copyright © 2019 Dylan. All rights reserved.

gcc -Wall -lm -std=c11  *.c  -o pagerank
./pagerank 0.85  0.00001  1000
valgrind  --leak-check=full --log-file=log ./pagerank 0.85 0.00001 1000
gedit log&
